### ISSUE TITLE
[Suggestion] Disable certain events

### ISSUE THREAD

**Issue by NoltoxGit** [Artillex-Studios/AxInventoryRestore#10]
Hello,
Would it be possible to disable some backup events in the plugin configuration please?

Example configuration:
```yml
list-categories-enabled:
  category-death: true/false
  category-join: true/false
  category-quit: true/false
  category-world_change: true/false
```
